### ISSUE TITLE
Add more detail to the readme.md

### ISSUE THREAD

**Issue by ebgoldstein** [envidynxlab/Networks_Barriers#1]
- [x] describe the project
- [x] requirements (i.e., maybe from `session-info`)
- [x] describe what each notebook does
- [x] explain the order in which to run reach notebook
- [x] data needed (and DOI/ URL link to data)

**Comment by SofiaAldabet** [comment]
I'm not sure what to add in the requirements section. I have pasted there all packages I have in the environment, although I didn't use all of them (I downloaded some to try things I didn't use at the end). Would it be better to keep only the most importat ones? Or only those that have to be imported in the notebooks?

**Comment by ebgoldstein** [comment]
we can deal with that later if need be... 
Last thing would be to describe the directory structure — does a user need to make any addiitonal folders? — like a `/data/` folder?
